### ISSUE TITLE
OpenCore has way too high resolution (gets out of the screen even on my second monitor)

### ISSUE THREAD

**Issue by AnErrupTion** [thenickdude/KVM-Opencore#11]
I'm trying to install Big Sur with its BaseSystem.dmg and QEMU. I'm using KVM OpenCore version 12. This issue also happened at version 10, however I could at least install the OS and use it. But here, first when booting to the bootloader the resolution is something like 1080p (which is fine because my screen is the same, just the borders going out of the screen) but now the resolution is even worse when going to the recovery (I can only see a gray screen and nothing else). This wasn't an issue when installing Catalina and still isn't.

**Comment by thenickdude** [comment]
My config.plist sets the resolution to 1920x1080, and this shouldn't change in the recovery environment.

Do you have "-vga vmware" set? That's the video adapter I test with.

**Comment by AnErrupTion** [comment]
I have set it to plain VGA, I'll test right now and give you the results.

**Comment by AnErrupTion** [comment]
Well it seems to work perfectly now.. I don't know if it was because I was setting the xres and yres myself or because of the plain VGA driver... Thanks!
