### ISSUE TITLE
Updating to Monterey

### ISSUE THREAD

**Issue by cagnulein** [thenickdude/KVM-Opencore#17]
Hi @thenickdude , sorry to bother you.
I'm upgrading from Bigsour to Monterey. Everything was fine on the previous version. I run the updater and then now it doesn't boot anymore. I follow your guide, so i updated opencore first, i checked that booted with bigsour and new opencore, i disabled the external VGA.
I attached a video showing the issue with the verbose mode on.
I will send you some coffees for sure if you're able to diagnose which is the issue.
Thanks!

[Screen Recording 2021-11-10 at 22.00.07.zip](https://github.com/thenickdude/KVM-Opencore/files/7515933/Screen.Recording.2021-11-10.at.22.00.07.zip)

**Comment by cagnulein** [comment]
in the end i'm restarting from a blank installation...let's see if this will work

**Comment by thenickdude** [comment]
So does it just hang forever at that 10% on the loading bar?

Note that during an upgrade it's likely to take 20 minutes of time computing a new seal for the new system volume, so a long hang here isn't unexpected.

**Comment by cagnulein** [comment]
@thenickdude yes. when i press CMD+V in the bootloader it hangs at the 10%. When i don't press the CMD+V it arrives more or less at the 30% and it hangs.

Yes i waited more than 3 hours after the update...Anyway i'm starting from scratch right now, let's see how it will go. Maybe it was just a bug of the Monterey installer after all :D

Thanks for getting back to me!

**Comment by cagnulein** [comment]
starting from a fresh install worked. Thanks anyway!
P.S. You should really put a buy me a coffee button somewhere, i would like to contribute to this (and probably other people will do it too)

**Comment by cagnulein** [comment]
argh unbelieavable paypal wants 5$ for sending you 10$! do you know any other methods to send you money? usually i'm using this https://www.buymeacoffee.com/cagnulein 
Do you have an account there @thenickdude  ?

Anyway Monterey on my HP Z420 is running awesome after the reset!

**Comment by thenickdude** [comment]
Most of those services are US-only

I think if you choose the option to send the money as a purchase rather than sending to a friend the effective fee ends up being way lower (like 20c + 3% or something like that)
