### ISSUE TITLE
Which GPU should I use on Monterey?

### ISSUE THREAD

**Issue by cagnulein** [thenickdude/KVM-Opencore#18]
Not a real issue, just a question :)

I was using a GT710 on Big sour and it was working good for my needs. Now apple removes kepler supports from Monterey so my question is: which GPU should i buy in order to have proxmox compatibility out of the box? I don't need any particular perfomances: i'm just using Xcode and iOS simulator on it.

Thanks

**Comment by thenickdude** [comment]
You can keep using your card using this patch:

https://github.com/chris1111/Geforce-Kepler-patcher

The only GPUs I can really recommend are the AMD RDNA 2 cards from this list:

https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#native-amd-gpus

RDNA 2 finally fixed the AMD Reset Bug that was found on older GPUs.

**Comment by cagnulein** [comment]
Thanks!
