### ISSUE TITLE
Can't start proxmox VM - error

### ISSUE THREAD

**Issue by HeyWatchOutDude** [thenickdude/KVM-Opencore#19]
Hi,

I followed the guide:
https://www.nicksherlock.com/2021/10/installing-macos-12-monterey-on-proxmox-7/

Sadly I get an error:
kvm: can't apply global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off: Property 'ICH9-LPC.acpi-pci-hotplug-with-bridge-support' not found
Use of uninitialized value $tpmpid in concatenation (.) or string at /usr/share/perl5/PVE/QemuServer.pm line 5465.
stopping swtpm instance (pid ) due to QEMU startup error
TASK ERROR: start failed: QEMU exited with code 1

Proxmox VE 7.0-13

My VM configuration:
args: -device isa-applesmc,osk="ourhardwork......" -smbios type=2 -device usb-kbd,bus=ehci.0,port=2 -cpu host,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off
agent: 1
balloon: 0
bios: ovmf
boot: order=ide2  
cores: 4
cpu: Penryn
efidisk0: local-lvm:vm-1100-disk-1,efitype=4m,size=4M
ide0: true-backup-raid1:iso/Monterey-recovery.img,cache=unsafe,size=3133040K
ide2: true-backup-raid1:iso/OpenCore-v15.iso,cache=unsafe,size=150M
machine: q35
memory: 4096
name: macserver
net0: virtio=DA:2E:F4:46:50:36,bridge=vmbr1,firewall=1,tag=20
numa: 1
ostype: other
scsihw: virtio-scsi-pci
smbios1: uuid=3038c254-24df-4505-a3e1-8981c96c913a
sockets: 1
vga: vmware
virtio0: local-lvm:vm-1100-disk-0,cache=unsafe,discard=on,size=64G
vmgenid: cd5218de-f8c4-4212-9733-bb1e2df14e33

Any idea what is wrong? My Proxmox host has an intel CPU.

**Comment by thenickdude** [comment]
This argument is only for QEMU 6.1+. If you're running an out of date QEMU package, omit this argument.
