### ISSUE TITLE
"Prohibited" sign appears on boot using OpenCore-v7 release

### ISSUE THREAD

**Issue by thenickdude** [thenickdude/KVM-Opencore#2]
If you always encounter a Prohibited (slashed-O) sign when trying to boot macOS or the macOS installer using my OpenCore-v7 release, please let me know here.

Reverting to the v5 release should solve this for Catalina VMs, but Big Sur is not compatible with my v5 release.

**Comment by iJuhan** [comment]
v5 release does indeed fix prohibited boot sign when booting Catalina installer.

**Comment by alexwhittemore** [comment]
ARGH! I spent the last maybe 3 hours trying to figure this out! Thanks for your diligence not only documenting all your work, but also opening issues to centralize troubleshooting!

Wanting to have a little more to go on before posting for help, I figured out (also using your guide at https://www.nicksherlock.com/2020/04/installing-macos-catalina-on-proxmox-with-opencore/) how to enable verbose mode

This is how my boot fails into the installer. 
<img width="722" alt="Screen Shot 2020-09-13 at 6 51 53 PM" src="https://user-images.githubusercontent.com/332827/93037461-529d7700-f5f7-11ea-9f4f-333db02b75b2.png">

Looks like its failing on 
[EB|`WL:PWLFNV] Err(0xE) @ GV wake-failure
whatever that means.

But! Switching to the V5 release as mentioned has me up and installing, so I guess, queue the new and different failure modes I haven't figured out yet! Hazzah!

Maybe it's time to go play some games like I actually set out to today...

**Comment by thenickdude** [comment]
Reading Verbose macOS logs is frustrating, because it usually turns out that half of the error messages are also printed on a perfectly normal, working boot, lol. Thanks for the log, I'll keep investigating.

**Comment by alexwhittemore** [comment]
What's the point of "verbose" if not to drastically over-report every little unexpected eventuality in head-spinning detail?

**Comment by sdgit** [comment]
I can confirm that V7 hangs and V5 works.

**Comment by ownstars** [comment]
Same on me, Catalina stuck with prohibited on v7 but works on v5.

**Comment by Shanduur** [comment]
v7 not working, v5 working good. 
Catalina 10.15.6.

**Comment by mattlathrop** [comment]
Add me to the list of V7 doesn't work but V5 does. Dell Poweredge 730xd Proxmox 6.2-4. Happy to help debug.

**Comment by nate2014jatc** [comment]
V7 Errors for Mojave, V5 seems to boot OK.
Proxmox: `pve-manager/6.2-11/22fb4983 (running kernel: 5.4.60-1-pve)`
Intel CPU:
```
Vendor ID:           GenuineIntel
CPU family:          6
Model:               30
Model name:          Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
```

**Comment by CamJohnson26** [comment]
Same, v7 fails with prohibited, v5 works. Thanks for documenting this issue!

**Comment by lnxbil** [comment]
Me too (v5 works, v7 fails), dual Xeon L5640 on Supermicro X8DAH, on `pve-manager/6.2-11/22fb4983 (running kernel: 5.4.60-1-pve)`

**Comment by seitzbg** [comment]
Same comments as above, v7 fails but v5 works:

Dual Xeon 2680V2 on a Dell R720XD
Linux pve2 5.4.44-2-pve #1 SMP PVE 5.4.44-2 (Wed, 01 Jul 2020 16:37:57 +0200) x86_64 GNU/Linux

**Comment by thenickdude** [comment]
I have a new v8 release available now for testing, based on OpenCore 0.6.2, please give it a go:

https://github.com/thenickdude/KVM-Opencore/releases/tag/v8

**Comment by iJuhan** [comment]
Can confirm v8 release fixed it. Already cloned it to the EFI partition. Thanks!

**Comment by eskild** [comment]
I can *not* confirm v8 fixes "prohibited" for Catalina. v5 works for me.

**Comment by Logicman111** [comment]
V8 doesn't work for me but v5 does.

**Comment by thenickdude** [comment]
Damn, I had hopes for this one. If only I could reproduce it on my machine...

**Comment by hansn74** [comment]
same here, V8 doesn't work, V5 does

**Comment by sayunkim** [comment]
v8 does not allow me to boot the ISO for Catelina 10.15.7.  v5 works, though.  :)

**Comment by un-fmunozs** [comment]
v5 works with Catalina, v8 doesnt for me


CPU(s) 8 x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (1 Socket)
--
Kernel Version Linux 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200)
PVE Manager Version pve-manager/6.2-4/9824574a

**Comment by zomfg** [comment]
same: v5 works, v7/8 fail
i5-7500 / 5.4.60-1-pve #1 SMP PVE 5.4.60-2

**Comment by jarekmor** [comment]
I encountered a "prohibited" sign on booting macOS Catalina with V8 release, too. I used the older V5 release instead and was able to install the OS. After successful installation I replaced: BOOTx64.efi, OpenCore.efi, OpenRuntime.efi and config.plist form V5 with new files from V8 release and the OS booted and it is working fine. Instead of graphical boot loader now I have only text one (attached screens). 
![Screenshot 2020-10-18 at 04 46 39](https://user-images.githubusercontent.com/56716603/96366870-424d5000-10ff-11eb-86d9-4472aa3d25a4.png)
![IMG_0765](https://user-images.githubusercontent.com/56716603/96366873-47aa9a80-10ff-11eb-9c74-5e4dbb3df4d0.jpg)
My HW is: Intel Xeon E5-2690, Linux 5.4.65-1-pve #1 SMP PVE 5.4.65-1, pie-manager/6.2-12.

**Comment by thenickdude** [comment]
@jarekmor if you also grab OpenCanopy.efi from v8 does it continue to work? That's the one that adds the GUI boot picker.

**Comment by jarekmor** [comment]
@thenickdude I have already copied all files from V8 and everything works now.

**Comment by thenickdude** [comment]
Hmm that's weird, so maybe v8 doesn't work with some initial setup task that Catalina needs to do on first boot (like rebuilding the kext cache maybe). This gives me something to investigate, thanks!

**Comment by 33b5e5** [comment]
I also can't boot Catalina on v8, but reverting to v5 resolved the issue. Please let me know what additional information would be helpful, if any.

**Comment by un-fmunozs** [comment]
Like @jarekmor mentioned, after installI swapped opencore 5 for opencore 8  and it was able to boot without problem 

![image](https://user-images.githubusercontent.com/9144791/96405200-59914980-11a2-11eb-9b8e-faefa5f7b846.png)

**Comment by thenickdude** [comment]
I was able to bisect the problem down to the following commit in VBoxHFS:

https://github.com/nms42/VBoxFsDxe/commit/28e274940491a2f5cb9fc951123dde6910ad28c5

I've now published v9 which is the same as v8, but reverts this VBoxHFS commit, and it will now boot the Catalina installer for me fine (as well as my Big Sur VM). Hopefully this solution works for everyone else too!

https://github.com/thenickdude/KVM-Opencore/releases/tag/v9

**Comment by zomfg** [comment]
v9 works for me 👍

**Comment by jarekmor** [comment]
V9 works! 
One comment: instead of bootloader icons I can see black screen only. But I hit Enter and installation started.

**Comment by thamerx** [comment]
V9 works great!

**Comment by harkdand** [comment]
Neither v9 or v5 boots.
CPU: AMD Ryzen 5 3600

Has anyone had luck with 3rd gen ryzen?

**Comment by thenickdude** [comment]
If you're using AMD you'll need to use -cpu penryn instead of -cpu host, or else you'll need to add a bunch of AMD kernel patches to config.plist:

    -cpu Penryn,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+avx2,+aes,+fma,+fma4,+bmi1,+bmi2,+xsave,+xsaveopt,check

**Comment by kiler129** [comment]
@thenickdude Indeed v9 works great! I think I found one small oversight: the main drive appears as ejectable/external. I tried poking around but I wasn't able to find any way of changing that:

- Disabling hotplug for drives on Proxmox does nothing
- Disk is not a PCIe device so I don't think it can be patched like ethernet `built-in`
- Some people suggested it's a behavior of OVMF but I wasn't able to find any details

**Comment by dmatora** [comment]
CPU: i5-8600K
This is what I get (even with v5 and v9).
<img width="671" alt="image" src="https://user-images.githubusercontent.com/647062/138244551-bbf36b19-863a-4b90-b0ec-1f274055a3ad.png">

**Comment by dmatora** [comment]
Ok I've taken commands from ESXi guide and combined with your guide to get full install image
```
hdiutil create -o /tmp/catalina -size 13000.1m -volname catalina -layout SPUD -fs HFS+J
hdiutil attach /tmp/catalina.dmg -noverify -mountpoint /Volumes/Catalina
/Applications/Install\ macOS\ Catalina.app/Contents/Resources/createinstallmedia --volume /Volumes/Catalina/
hdiutil eject -force /volumes/Install\ macOS\ Catalina/
hdiutil convert /tmp/catalina.dmg -format UDRW -o Catlina-Full-installer.iso
```
But OpenCore doesn't recognise this image mounted same way as small one.
Is that fixable?

**Comment by dmatora** [comment]
Also when I try to mount install iso that work in Vmware as CD image, to Proxmox, also as CD image, it doesn't get recognised by OpenCore, either. Any clue?
