### ISSUE TITLE
Multiple Monitor Setup

### ISSUE THREAD

**Issue by yqlbu** [thenickdude/KVM-Opencore#20]
Hi, I successfully got the KVM Hackintosh up-and-running on Proxmox 7.0.1 followed by your guide. The GPU passthrough (5500XT) has been successful as well. However, for some reasons, it does not connect to all monitors (I have four monitors), ONLY limited to 2 monitors. Are there any parameters in the `config.plist` that enable this feature?

**Comment by Medizinmann-MD** [comment]
Hi, 
I am running a W6600(MacOS 12.2.1 and Proxmox 7.1) with 4 monitors and it works just fine. I only added the "agdpmod=pikera" in Boot-args.

I followed this guide:
https://blog.quindorian.org/2018/03/building-a-2u-amd-ryzen-server-proxmox-gpu-passthrough.html/

I had a faulty dp-port to hdmi cable - I needed to replace. Did you test different cables?

**Comment by yqlbu** [comment]
Yah. Unfortunately, it doesn't work for me.
