### ISSUE TITLE
Mentioning rdrand branch on https://www.nicksherlock.com/2021/10/installing-macos-12-monterey-on-proxmox-7/ 

### ISSUE THREAD

**Issue by dme26** [thenickdude/KVM-Opencore#21]
First, thank you very much for your work writing and sharing https://www.nicksherlock.com/2021/10/installing-macos-12-monterey-on-proxmox-7/ 

I successfully performed an installation on older Apple hardware with a CPU that (I believe) needs the [SurPlus patch](https://github.com/reenigneorcim/SurPlus).

The tiny issue: I note that the SurPlus patch is applied within your `rdrand` branch. could that branch and its purpose be mentioned on your (aforementioned) guide page, possibly?

While I think it likely that many users will check the branches present in your repository, I failed to do so, and only noticed that you'd already preempted my commit, after applying my own equivalent change to a fork of your repository.

**Comment by thenickdude** [comment]
I've now included it in my v16 release for people still on 12.0 though, thanks for the nudge!
