### ISSUE TITLE
New install Monterey - boot stops at Apple logo

### ISSUE THREAD

**Issue by BaoNTGH** [thenickdude/KVM-Opencore#22]
Hi,

Thanks for the work. I'm trying to install on Proxmox 7.1-7 VM and OpenCore-v16. Here is my VM configuration (OSK was updated accordingly:

> args: -device isa-applesmc,osk="OSK" -smbios type=2 -device usb-kbd,bus=ehci.0,port=2 -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off -cpu host,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc
> bios: ovmf
> boot: order=virtio0;ide2
> cores: 12
> cpu: Penryn
> efidisk0: local-lvm:vm-100-disk-1,efitype=4m,size=4M
> ide0: nas-proxmox:iso/Monterey.iso,cache=unsafe,size=15000M
> ide2: nas-proxmox:iso/OpenCore-v16.iso,cache=unsafe
> machine: q35
> memory: 16384
> meta: creation-qemu=6.1.0,ctime=1642041513
> name: MYMAC
> net0: vmxnet3=DE:CC:DD:5E:6A:D0,bridge=vmbr0,firewall=1
> numa: 0
> ostype: other
> scsihw: virtio-scsi-pci
> smbios1: uuid=c9d77b02-a239-48f0-be1e-ff5ed30af7ee
> sockets: 1
> vga: vmware
> virtio0: local-lvm:vm-100-disk-0,cache=unsafe,discard=on,size=200G
> vmgenid: 

Boot stops at the Apple logo. With verbose, it shows this:

![image](https://user-images.githubusercontent.com/29285869/149428937-06825676-d88e-4cb3-b866-5bb20e3bd753.png)

Would be there any recommendation?

Thanks,
Bao

**Comment by thenickdude** [comment]
cores=12 doesn't work, use a power of two for your core count
