### ISSUE TITLE
Cannot set one sockets with multiple cores using custom config.plist

### ISSUE THREAD

**Issue by BaoNTGH** [thenickdude/KVM-Opencore#23]
Hi,

This is not an issue but just a question. With your OpenCore package, everything worked fine: I create VM (in Proxmox) that has 1 socket and 8 cores. I installed Montery following your guide, everything also worked fine. When making VM bootable without CD, I'm trying to apply my OpenCore version (from my standalone hackintosh), it doesn't allow me to set **1 socket and 8 cores**, but if I set **4 sockets, each with 1 core** then everything works fine.

I'm trying to compare 2 config.plist but kinda lost which part actually causes that difference. Would you have any pointers?

Thanks,

**Comment by thenickdude** [comment]
Why not just use my OpenCore image instead? You can copy that one to your disk. 

It would be one of the kernel patches, the core topology one.

**Comment by BaoNTGH** [comment]
Just OCD I guess. I'm seeing quite a lot of things not needed for my system. Instead of cleaning up your image, I just need one thing about this core thing for my image.

**Comment by BaoNTGH** [comment]
Found it, in case anyone interested: set ProvideCurrentCpuInfo to true in Kernel > Patch of config.list
