### ISSUE TITLE
hotplug a sata/virtio disk to macOS

### ISSUE THREAD

**Issue by blarrow** [thenickdude/KVM-Opencore#25]
I want to hotplug a new disk to macOS, and I test sata and virtio hotplug, but it not works.
On qemu side the new disk is already attached with monitor info block shows. 
But on guest macOS side do not find the hotplug new disk.
Does anyone know about this issue, is it related to OpenCore?

Version Lists:
* pve7 with QEMU6.0.0
* OpenCore v13
* macOS 12.1

**Comment by thenickdude** [comment]
Hmm I know there's an option to mark SATA ports as "external" in OpenCore config, because people commonly complain that their harddisk appears as an external drive and macOS offers to eject it, and this can be fixed with the same option. 

It's likely that marking it as external is required for macOS to consider it a valid hotplug port.

**Comment by blarrow** [comment]
> Hmm I know there's an option to mark SATA ports as "external" in OpenCore config, because people commonly complain that their harddisk appears as an external drive and macOS offers to eject it, and this can be fixed with the same option.
> 
> It's likely that marking it as external is required for macOS to consider it a valid hotplug port.

Do you no which option, in OpenCore config.plist or ACPI files?
I find the [reddit]( https://www.reddit.com/r/hackintosh/comments/f0cc4t/internal_drives_shown_as_external_opencore_amd/) , but the no built-in in our config.plist

**Comment by thenickdude** [comment]
No I don't, sorry

**Comment by thenickdude** [comment]
Maybe ask Reddit's /r/hackintosh, but keep it a secret that you're using a VM because otherwise they will delete your post

**Comment by sickcodes** [comment]
Replied to OP:

https://github.com/Leoyzen/KVM-Opencore/issues/20#issuecomment-1046054760
