### ISSUE TITLE
upgraded to 0.7.7 and screen becomes blank just before the login window

### ISSUE THREAD

**Issue by nferruzzi** [thenickdude/KVM-Opencore#26]
Hello,
just attempted to upgrade opencore on my VM (BigSur + 6900xt passthrough) the system boot and I can select the drive, but after the apple logo / verbose output the display "reset" and I get to a blank screen. Going back to a previous version of OpenCore (I don't know exactly one but its from november of last year) simply fix it. 
Any idea of what new option in opencore could cause this ? usually upgrading OC works flawless and this is the first time that it breaks something. My goal is to prepare my system to upgrade to monterey but at the moment Im stuck with this problem. Thanks for any suggestion.

Edit:
disabling the 6900xt pt makes the system works

**Comment by thenickdude** [comment]
Did you also update to my newest config.plist? You might have accidentally removed agdpmod=pikera from your boot args in the process.

**Comment by nferruzzi** [comment]
actually I don't have that option on any of my config.plist files ; it doesn't seem to be on the one Ive downloaded from here too

**Comment by thenickdude** [comment]
Try adding it

**Comment by nferruzzi** [comment]
ehmm.. how do I do that ?

**Comment by thenickdude** [comment]
How do you edit config.plist? I have instructions here, see the section "Editing your OpenCore/EFI settings":

https://www.nicksherlock.com/2021/10/installing-macos-12-monterey-on-proxmox-7/

You'll be adding it alongside the keepsyms=1 setting that's there already (separated by a space).

**Comment by nferruzzi** [comment]
I've spotted this error, could be related.

Failed to send SMC number of eGPU P states (16) due to 0x82!

as a separate note, without rebooting the pc and by just going back to the previous EFI img it works .. so its definitely something with this new version

**Comment by nferruzzi** [comment]
After some time debugging I think Im getting close ..  I get a black screen but the VM is actually working . Connecting via screen sharing I can see that it has "2 displays" 
1. is the virt manager one, and basically results as the` "main one"
2. the 6900xt - and using IORegistryExplorer Ive noticed that all its frame buffers have the connector-type disabled..

somehow this new version manages to keep the graphic/display from virt manager one up and running which is something that wasn't happening before and, I guess, macos decides to disable the output ports from the GPU for some reasons.

I tried to patch the connector-type with  whatevergreen but so far no luck.

**Comment by thenickdude** [comment]
Did you try removing the virtual display adapter? Or was that your initial configuration?

**Comment by nferruzzi** [comment]
yes I did removed and basically tried all the combinations by now .. no matter the configuration I put on virt, with the previous version the radeon is working and the "Internal display" is not loaded

Hardware -> Graphics/Display -> Display 
  Type:	GPU
  Device ID:	0x0405
  Revision ID:	0x0000
  Kernel Extension Info:	No Kext Loaded
  Vendor ID:	0x15ad


Switching to new version the kext gets loaded and somehow prevents the radeon from getting the "display" . Im trying now upgrading all weg+lilo+oc by hand

**Comment by nferruzzi** [comment]
At the end I got it working reverting to OpenCore 0.7.4 `agdpmod=pikera` and monterey 12.3.1 (the most recent minor). Apparently on BigSur pikera is not needed and I had to explore the proper configuration installing a new VM; glad at the end it worked well. Closing this issue. Thanks
