### ISSUE TITLE
12.3.1 problem

### ISSUE THREAD

**Issue by hide74** [thenickdude/KVM-Opencore#28]
I've tried to my environment to 12.3.1, but I failed.
I could not boot normally.
Until 12.2.1, I had no probllem.
Is there any idea to resolve this problem?

**Comment by thenickdude** [comment]
12.3.1 works fine for me. You can try building a full installer and reinstall macOS using that (it'll keep your data). The full installer seems more reliable than the regular updater.

**Comment by hide74** [comment]
Thanks a lot for your feedback.
I'll try fullinstaller as your recomendation.

**Comment by hide74** [comment]
I'm using RX470.
