### ISSUE TITLE
Monterey 12.3.1 crush everyday

### ISSUE THREAD

**Issue by iamjimmycheng** [thenickdude/KVM-Opencore#29]
I already install 12.3.1+ opencore V16.

Everything seems normally in the procedure.

After installation,i try the uhd630 passthrough.

After that,the mac system crush everyday.

I do not know what's wrong with it.

**Comment by thenickdude** [comment]
I can't assist with that. If you were using i915ovmfPkg then see this guide for a possible solution:

https://github.com/patmagauran/i915ovmfPkg/wiki/DVMT-Pre-Alloc---Stolen-Memory-Issues
