### ISSUE TITLE
Documentation can be improved

### ISSUE THREAD

**Issue by kiler129** [thenickdude/KVM-Opencore#3]
First of all an amazing extension of Leoyzen work! I'm sorry for the title of the issue upfront, but I think multiple things are related.

1. **Documentation discoverability**
Initially I discovered this repo via https://www.nicksherlock.com/2020/04/installing-macos-catalina-on-proxmox-with-opencore/ - maybe this documentation can be included & versioned on GH (maybe a GH page?) so it's always updated to the version of files and other people can contribute to it?

If you're ok with that I can convert the article into a logical set of markdowns.

2. **Penryn faking**
The recommendation to use Penryn CPU emulation is slightly misguided IMHO. While it certainly works it may cause instability in some apps which don't verify instructions but the CPU.
With modern CPUs supported officially by the macOS (e.g. Xeon E3-12xx or something like i5/i7) the real CPU can be presented to the guest which is even better.

3. **Proxmox & booting**
By default, at least in 6.2, the default boot order will start from `sata0` (empty QEmu drive) instead of `ide0` (OC). I think it should be added to the instruction as it may be confusing for beginners.

4. **One size doesn't always fits all**
This is probably my biggest point. Everybody here certainly believes in open source. This repo & the article is an amazing piece of work. However, after installation I had a feeling of "ok, what's next?". I will like to shape the installation to my own needs (e.g. I don't need GPU passthrough or USB pass, maybe I can simplify it?).
What I'm talking about here is it will be great to describe bigger overarching points about what is actually being done, why given kexts are loaded, provide links to read further etc, so that everyone doesn't have to reinvent the wheel from scratch :)

I'm saying this from a perspective of a person who was involved in the community for long time, but left years ago. The toolset changed, a lot of the things are the same, the idea is similar. However, it's extremely hard to go back and see the changes where there are two types of resources:
 - full tutorials step-by-step to get a working version and forget
 - extremely fine-grained resources like OC manual

This is I think a great candidate for a third type combining both: step-by-step tutorial for a working copy with some hooks to more detailed resources on a given overarching step.

**Comment by kholia** [comment]
@kiler129 PRs are open. Thank you!

**Comment by thenickdude** [comment]
The goal of this repo is just to be a sourcecode dump for me, the guides are all on my blog. No documentation will be added here. 

Points 2 3 and 4 are already covered on the blog.

**Comment by kiler129** [comment]
@thenickdude ohhh... I see it now :) I think I misunderstood the relationship of this repo to upstream.
@kholia About which PRs are you talking about? Or are suggesting to open some for the upstream repo?

Nicholas, while you closed this issue what do you & @kholia think about adding an alternative config with no Penryn emulation and settings more suitable for a server (i.e. no GPU pass, no audio etc). This could be really helpful for people setting up for e.g. automatic builds of iOS software.
