### ISSUE TITLE
macOS 13 Ventura keeps restarting during boot

### ISSUE THREAD

**Issue by blarrow** [thenickdude/KVM-Opencore#33]
With OpenCore-v16 and disable quirk AvoidRuntimeDefrag in Booter Quirks and add -lilubetaall

When install macOS looks as well, but it keeps restarting during boot
Serial logs show then panic logs:

bufattr_get_apfs:7764: Only accept buf I/O, no raw disk access
disk3s4: device is not readable.
Debugger called: <panic>
IOPlatformPanicAction -> AppleAHCIDiskDriver
IOPlatformPanicAction -> AppleAHCIDiskDriver
IOPlatformPanicAction -> AppleSMC
panic(cpu 1 caller 0xffffff8001a68d33): Possible memory corruption: pmap_pv_remove(0xffffff905ef89600,0x7ff94c405000,0x6, 0x6efe, 0xffffffa05d3e39d4, 0xfffffe96ae58a028): null pv_list, priors: 1 @pmap_internal.h:903
NULL bsd_info pointer
Panicked task 0xffffff952b20a988: 1 threads: unknown task
Backtrace (CPU 1), panicked thread: 0xffffff8b91f9a4e0, Frame : Return Address
0xffffffa05d3e35d0 : 0xffffff80019323dd mach_kernel : _handle_debugger_trap + 0x4ad
0xffffffa05d3e3620 : 0xffffff8001a9ab56 mach_kernel : _kdp_i386_trap + 0x116
0xffffffa05d3e3660 : 0xffffff8001a89df0 mach_kernel : _kernel_trap + 0x3e0
0xffffffa05d3e36b0 : 0xffffff80018cd951 mach_kernel : _return_from_trap + 0xc1
0xffffffa05d3e36d0 : 0xffffff80019326bd mach_kernel : _DebuggerTrapWithState + 0x5d
0xffffffa05d3e37c0 : 0xffffff8001931d69 mach_kernel : _panic_trap_to_debugger + 0x1a9
0xffffffa05d3e3820 : 0xffffff800211613b mach_kernel : _panic + 0x84
0xffffffa05d3e3910 : 0xffffff8001a68d33 mach_kernel : _pmap_remove_range + 0xcd3
0xffffffa05d3e3a00 : 0xffffff8001a69001 mach_kernel : _pmap_remove_options + 0x231
0xffffffa05d3e3a50 : 0xffffff80019ef44b mach_kernel : _vm_map_switch + 0x1b1b
0xffffffa05d3e3aa0 : 0xffffff80019ee5a9 mach_kernel : _vm_map_switch + 0xc79
0xffffffa05d3e3bd0 : 0xffffff80019edb29 mach_kernel : _vm_map_switch + 0x1f9
0xffffffa05d3e3c30 : 0xffffff80019f5e27 mach_kernel : _vm_map_terminate + 0xe7
0xffffffa05d3e3c80 : 0xffffff8001971845 mach_kernel : _task_terminate_internal + 0x2b5
0xffffffa05d3e3cc0 : 0xffffff80019166dc mach_kernel : _ipc_port_release_send_and_unlock + 0x15c
0xffffffa05d3e3d20 : 0xffffff800197668c mach_kernel : _task_deliver_crash_notification + 0x21c
0xffffffa05d3e3d70 : 0xffffff8001984442 mach_kernel : _thread_terminate_self + 0x632
0xffffffa05d3e3e50 : 0xffffff8001988f93 mach_kernel : _thread_apc_ast + 0xa3
0xffffffa05d3e3e80 : 0xffffff800192884c mach_kernel : _ast_taken_user + 0x14c
0xffffffa05d3e3eb0 : 0xffffff80018cd91d mach_kernel : _return_from_trap + 0x8d
NULL bsd_info pointer

Process name corresponding to current thread (0xffffff8b91f9a4e0): Unknown
Boot args: -v keepsyms=1 -lilubetaall debug=0x12a msgbuf=1048576 serial=5 -cpuid -topo slide=11

Mac OS version:
22A5266r

Kernel version:
Darwin Kernel Version 22.0.0: Tue May 24 20:31:35 PDT 2022; root:xnu-8792.0.50.111.3~5/RELEASE_X86_64
Kernel UUID: 198748B0-2858-345A-957A-45C9ACB4C2F2
roots installed: 0
KernelCache slide: 0x0000000001600000
KernelCache base:  0xffffff8001800000
Kernel slide:      0x0000000001610000
Kernel text base:  0xffffff8001810000
__HIB  text base: 0xffffff8001700000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: NO (0xe00002bc)
Hibernation exit count: 0

System uptime in nanoseconds: 32431910640
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000078d2e1462
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000003d16e3e4548 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff805d269000 - 0xffffffa05d269000
  . PGZ   : 0xffffff805d269000 - 0xffffff8060a6a000
  . VM    : 0xffffff8060a6a000 - 0xffffff852ced0000
  . RO    : 0xffffff852ced0000 - 0xffffff86c659c000
  . GEN0  : 0xffffff86c659c000 - 0xffffff8b92a02000
  . GEN1  : 0xffffff8b92a02000 - 0xffffff905ee68000
  . GEN2  : 0xffffff905ee68000 - 0xffffff952b2ce000
  . GEN3  : 0xffffff952b2ce000 - 0xffffff99f7735000
  . DATA  : 0xffffff99f7735000 - 0xffffffa05d269000
  Metadata: 0xffffff8022757000 - 0xffffff8042757000
  Bitmaps : 0xffffff8042757000 - 0xffffff804cf57000

last started kext at 15706780662: >DiskImages.SparseDiskImage	493.0.0 (addr 0xffffff80040b0000, size 8192)
loaded kexts:
as.acidanthera.BlueToolFixup	2.6.2
as.acidanthera.BrcmFirmwareStore	2.6.2
as.vit9696.!AALC	1.6.9
as.vit9696.WhateverGreen	1.5.7
as.vit9696.Lilu	1.6.0
>DiskImages.SparseDiskImage	493.0.0
>DiskImages.ReadWriteDiskImage	493.0.0
>DiskImages.CryptoEncoding	493.0.0
>DiskImages.UDIFDiskImage	493.0.0
>DiskImages.RAMBackingStore	493.0.0
>DiskImages.HTTPBackingStore	493.0.0
>DiskImages.FileBackingStore	493.0.0
>!APlatformEnabler	2.7.0d0
>AGPM	130
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AGraphicsDevicePolicy	7.1.14
>!AUpstreamUserClient	3.6.9
>!AMCCSControl	1.16
@AGDCPluginDisplayMetrics	7.1.14
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHV	1
>!ADiskImages2	177
>!A16X50ACPI	3.2
>!AFIVRDriver	4.1.0
>!A!ISlowAdaptiveClocking	4.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!AAHCIPort	361
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.apfs	2127.0.0
@filesystems.hfs.kext	606
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
>!AHPET	1.8
>!AACPIButtons	6.1
>!ARTC	2.0.1
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AUserConsent	1
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	402
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
@kec.Compression	1
@kec.!AEncryptedArchive	1
>DiskImages.KernelBacked	493.0.0
|IOAVB!F	1100.15
@plugin.IOgPTPPlugin	1100.31
>!UAudio	420.16
>!AAudioClockLibs	200.5
@kext.triggers	1.0
>!AGraphicsControl	7.1.14
>!ASMBus!C	1.0.18d1
|IOSMBus!F	1.1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	400.1
@vecLib.kext	1.2.0
>IOHIDPowerSource	1
|IO!BSerialManager	9.0.0
|IO!BPacketLogger	9.0.0
|IO!BHost!CUSBTransport	9.0.0
|IO!BHost!CUARTTransport	9.0.0
|IO!BHost!CTransport	9.0.0
>IO!BHost!CPCIeTransport	9.0.0
|CSR!BHost!CUSBTransport	9.0.0
|Broadcom!BHost!CUSBTransport	9.0.0
|Broadcom!B20703USBTransport	9.0.0
>!ARSMChannel	1
|IORSM!F	1
>!AIPAppender	1.0
>!ASMBusPCI	1.0.14d1
|IONDRVSupport	597
>!A16X50Serial	3.2
@!AGPUWrangler	7.1.14
@!AGraphicsDeviceControl	7.1.14
|IOGraphics!F	597
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>driverkit.serial	6.0.0
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AXsanScheme	3
|IOAHCIBlock!S	341
>!AVirtIO	174
|IOSerial!F	11
|IOAHCI!F	301
>usb.!UEHCIPCI	1.2
>usb.!UEHCI	1.2
>!ABSDKextStarter	3
|IOSurface	327.1
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	10.1.25
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IOHID!F	2.0.0
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOTimeSync!F	1100.31
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	546
|IOUSBMass!SDriver	228
|IOSCSIBlockCommandsDevice	473.0.0
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	473.0.0
>!AMobileFileIntegrity	1.0.5
$!AImage4	5.0.0
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
|CoreAnalytics!F	1
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	12.0
Attempting to commit panic log to NVRAM

**Comment by thenickdude** [comment]
v16 is not intended to support Ventura, I really doubt it is up to date enough to achieve it.

**Comment by thenickdude** [comment]
I've now released v17 which updates OpenCore to add Ventura support:

https://github.com/thenickdude/KVM-Opencore/releases/tag/v17
