### ISSUE TITLE
Proxmox MacOS no Install option available and with shell stuck on Apple Logo

### ISSUE THREAD

**Issue by KBapna** [thenickdude/KVM-Opencore#34]
100.conf file

agent: 1
args: -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" -smbios type=2 -device usb-kbd,bus=ehci.0,port=2 -global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off -cpu Penryn,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+avx2,+aes,+fma,+fma4,+bmi1,+bmi2,+xsave,+xsaveopt,+rdrand,check
balloon: 0
bios: ovmf
boot: order=ide2;ide0;virtio0;net0
cores: 2
cpu: Penryn
efidisk0: local:100/vm-100-disk-0.qcow2,efitype=4m,size=528K
ide0: local:iso/Monterey_12.3.1_v17.3.03.iso,cache=unsafe,size=14000M
ide2: local:iso/OpenCore-v17.iso,cache=unsafe,size=150M
machine: q35
memory: 2046
meta: creation-qemu=6.2.0,ctime=1655551433
name: MacOS
net0: virtio=something,bridge=vmbr0,firewall=1
numa: 0
ostype: other
scsihw: virtio-scsi-pci
smbios1: uuid=some id
sockets: 1
vga: vmware
virtio0: local:100/vm-100-disk-1.qcow2,cache=unsafe,discard=on,size=100G
vmgenid: some id

<img width="898" alt="image" src="https://user-images.githubusercontent.com/107757630/174438997-e5c43f28-1a12-4c94-8595-5658a6e8d0bc.png">
<img width="1118" alt="Screenshot 2022-06-18 183301" src="https://user-images.githubusercontent.com/107757630/174438920-78122ca9-27aa-4c45-ac3b-e835f8e45fc8.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/107757630/174438949-e01e47d8-faca-4da4-a42d-d8ec696b3f64.png">

**Comment by thenickdude** [comment]
Most likely your installer wasn't generated according to the instructions. It must be a GPT-partitioned hard disk image to work with my instructions.

**Comment by KBapna** [comment]
I uploaded the new .img files and made a fresh VM still it got stuck on apple logo.

**Comment by thenickdude** [comment]
What's your host's CPU model?

**Comment by KBapna** [comment]
Yes installer icon appears now but no progress bar under apple logo.
It is AMD A4 dual core 2GHz

**Comment by thenickdude** [comment]
I think you'll need to boot in Verbose mode so you can capture the error log, press Win/Cmd + V once and release it before pressing enter to select the installer.

**Comment by KBapna** [comment]
![image](https://user-images.githubusercontent.com/107757630/174442567-4574b247-4004-4879-a9d6-06b1c5a40169.png)
![image](https://user-images.githubusercontent.com/107757630/174442570-0c1fefe7-1763-4f0a-8972-70efd4476cea.png)

**Comment by thenickdude** [comment]
Ah, it's crashing because your CPU misses some kind of required instruction set. I'm not sure what one is the problem, because in theory your CPU has SSE4.2 and SSSE3 support. Maybe it misses POPCNT? 

Can you check the list of supported CPU features in Proxmox by running "cat /proc/cpuinfo".

**Comment by KBapna** [comment]
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 18
model           : 1
model name      : AMD A4-3305M APU with Radeon(tm) HD Graphics
stepping        : 0
microcode       : 0x3000027
cpu MHz         : 1951.702
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips        : 3793.33
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate cpb

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 18
model           : 1
model name      : AMD A4-3305M APU with Radeon(tm) HD Graphics
stepping        : 0
microcode       : 0x3000027
cpu MHz         : 2157.086
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips        : 3793.33
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate cpb

**Comment by thenickdude** [comment]
Try adding "sse4a" to the list of CPU flags in your VM "args"

**Comment by KBapna** [comment]
![image](https://user-images.githubusercontent.com/107757630/174443012-9b4ae072-bc49-4f1d-94a1-cd7ff7238f01.png)
![image](https://user-images.githubusercontent.com/107757630/174443013-11cf5020-ee51-48f2-9efc-a646e956ec4a.png)
Still same problem.

**Comment by thenickdude** [comment]
Sorry, I think your CPU misses required instruction sets.
