### ISSUE TITLE
update opencore to 0.8.3

### ISSUE THREAD

**Issue by si458** [thenickdude/KVM-Opencore#36]
update opencore to 0.8.3

**Comment by NeariX67** [comment]
Have you tried booting into Ventura with this?

**Comment by si458** [comment]
Is the a reason this was closed?

**Comment by thenickdude** [comment]
My release has been based on 0.8.5 or newer since October

**Comment by si458** [comment]
> My release has been based on 0.8.5 or newer since October 

Oh Ok no worries

IvMust have a look at it again then as I'm sure the last time I tried it in January it was older than 0.8.3?
