### ISSUE TITLE
blank display on Ventura after install RX580 with OC v19

### ISSUE THREAD

**Issue by mbagusrd** [thenickdude/KVM-Opencore#46]
Hi, I'm using OC v19 and successfully install Ventura with qemu-kvm/virtmanager default vga. But after install RX580 via GPU Passthrough I got blank screen after Apple boot logo. I'm not having this problem with Monterey before.

Is there any solution about this problem? Thanks in advance.

**Comment by NeariX67** [comment]
We also covered this in #45
See [this comment](https://github.com/thenickdude/KVM-Opencore/issues/45#issuecomment-1306810894)

**Comment by NeariX67** [comment]
I also ran into this problem months ago, but never got the time to test the previous solution for this

**Comment by mbagusrd** [comment]
> We also covered this in #45 See [this comment](https://github.com/thenickdude/KVM-Opencore/issues/45#issuecomment-1306810894)

I've tried, then I got this Error

> Error starting domain: internal error: qemu unexpectedly closed the monitor: 2022-11-10T10:36:06.138873Z qemu-system-x86_64: can't apply global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off: Property '.acpi-pci-hotplug-with-bridge-support' not found

**Comment by thenickdude** [comment]
This means that your QEMU version is old enough that it doesn't have the problem that this argument fixes, so you don't need it.

Make sure you don't still have an emulated video device attached.

**Comment by NeariX67** [comment]
I got the time to install my RX 460 and tried to run Ventura.


I'm stuck here:
![IMG_6364](https://user-images.githubusercontent.com/31779313/201198309-3865bc36-d0a8-4909-b9bd-b079608343f4.jpg)
[Current XML Config](https://github.com/thenickdude/KVM-Opencore/files/9984381/Current.md)

**Comment by mbagusrd** [comment]
> This means that your QEMU version is old enough that it doesn't have the problem that this argument fixes, so you don't need it.
> 
> Make sure you don't still have an emulated video device attached.

okay, maybe I need to update my Qemu. 

I'm sure I dont have emulated video attached

**Comment by ownway88** [comment]
> 

I got exactly the same error when I install a RX580...

**Comment by ownway88** [comment]
> > I got the time to install my RX 460 and tried to run Ventura.
> > I'm stuck here: ![IMG_6364](https://user-images.githubusercontent.com/31779313/201198309-3865bc36-d0a8-4909-b9bd-b079608343f4.jpg) [Current XML Config](https://github.com/thenickdude/KVM-Opencore/files/9984381/Current.md)
> 
> I got exactly same error with RX580 installed.
> 
> My CPU is 10700k. I tried to install Ventura on physical machine with opencore instead of PVE virtual machine, it works perfectly. I tried to change the platform to iMac20,1 as suggested in opencore for comet lake, still the same error.
> 
> Is there anywhere I can futher look at?

An update on this one. After deeper look, I realize the problem in my case was that the IOMMU was not enable. After enabling it in proxmox(lots of tutorials online), I am able to book into Ventura successfully.

**Comment by thenickdude** [comment]
How did your VM even start with no IOMMU available?

**Comment by ownway88** [comment]
> How did your VM even start with no IOMMU available?

To be clear, I did not set the grub file so that the magic words "DMAR: IOMMU enabled" were not shown. The IOMMU in BIOS was enabled. Without the grub file being correctly set, I was able to boot into Ventura without dGPU. As long as I pass thru my RX580, the same error was seen.

**Comment by mbagusrd** [comment]
my xmlconfig is similar with this [xml](https://github.com/thenickdude/KVM-Opencore/files/9984381/Current.md)

And I guess the problem is caused by processor config, when I use Penryn (no avx2) + default vga I can run Ventura without problem, but after I attach RX580 ventura got blank screen after apple boot screen, and when I set cpu to host-passthrough I stuck at boot screen and sometimes auto restart.

FYI i'm using Ryzen 5 5600g (avx2 available) and I couldnt find the working conf yet.

**Comment by thenickdude** [comment]
AMD needs cpu=Haswell-noTSX

**Comment by mbagusrd** [comment]
> AMD needs cpu=Haswell-noTSX

Is it works with Ryzen 5 5600G?

**Comment by thenickdude** [comment]
Almost certainly

**Comment by mbagusrd** [comment]
sorry, i've tried but still no luck

@thenickdude can you tell me what is wrong with my xml

[https://github.com/mbagusrd/files/raw/main/ventura.xml](please check)

**Comment by thenickdude** [comment]
The definition for your HDMI audio device is wrong, it's currently:

    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x1"/>
      </source>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </hostdev>

But it needs to be at the same address as the GPU, but with function=0x1:

    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x1"/>
      </source>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x1"/>
    </hostdev>

This won't solve your problem, though, I'm not sure what's causing that.

**Comment by mbagusrd** [comment]
Alhamdulillah/thank god

Today I run MacOS Ventura with GPU Passthrough successfully via qemu command line without virt manager.

[screenshot](https://ibb.co/7vBkXDB)

[Qemu Command](https://github.com/mbagusrd/OSX-KVM/blob/bagus/bootVenturaRX.sh)

thank you so much to all participants in this issue, special thanks to @thenickdude.

**Comment by thunfischente** [comment]
I can passthrough GPU to Windows 11, but it can't work with macOS Monterey, I can boot as normal when attach GPU but it doesn't show in about this Mac as well as system preferences, how can I fix now please!

**Comment by thunfischente** [comment]
> Alhamdulillah/thank god
> 
> Today I run MacOS Ventura with GPU Passthrough successfully via qemu command line without virt manager.
> 
> [screenshot](https://ibb.co/7vBkXDB)
> 
> [Qemu Command](https://github.com/mbagusrd/OSX-KVM/blob/bagus/bootVenturaRX.sh)
> 
> thank you so much to all participants in this issue, special thanks to @thenickdude.

which version of proxmox are you using when installing Ventura with passthrough GPU

**Comment by mbagusrd** [comment]
> which version of proxmox are you using when installing Ventura with passthrough GPU

I use latest Linux Mint and Qemu 6.2

**Comment by mihalski** [comment]
Are you using vendor-reset and have a bios loadable from a file? I was unable to get my RX590 to work until I configured those two things.

**Comment by mbagusrd** [comment]
I'm not using VGA bios file, I just made little mod in qemu script file and then I found it works, hehe

**Comment by thunfischente** [comment]
I have 2 GPU, one is Nvidia GT730 for Proxmox uses, another is RX 570, I can passthrough RX570 to Windows 11, everything is checked but when I attach it to macOS, it can't work, don't know why. Which guides do you use to config your system to passthrough to macOS please

**Comment by thunfischente** [comment]
> > which version of proxmox are you using when installing Ventura with passthrough GPU
> 
> I use latest Linux Mint and Qemu 6.2

you meant that Proxmox is 7.3-3 and u use Qemu 6.2? Thank you

**Comment by thunfischente** [comment]
> Are you using vendor-reset and have a bios loadable from a file? I was unable to get my RX590 to work until I configured those two things.

can you passthrough RX590? I can start VM normally but it doesn't recognise RX570

**Comment by mbagusrd** [comment]
> I have 2 GPU, one is Nvidia GT730 for Proxmox uses, another is RX 570, I can passthrough RX570 to Windows 11, everything is checked but when I attach it to macOS, it can't work, don't know why. Which guides do you use to config your system to passthrough to macOS please

I dont know how to configure it in Proxmox, if you understand Qemu config you may see this [file](https://github.com/kholia/OSX-KVM/blob/master/boot-passthrough.sh). 

I was able to boot macOS Monterey with RX580 successfully.

**Comment by thunfischente** [comment]
> > I have 2 GPU, one is Nvidia GT730 for Proxmox uses, another is RX 570, I can passthrough RX570 to Windows 11, everything is checked but when I attach it to macOS, it can't work, don't know why. Which guides do you use to config your system to passthrough to macOS please
> 
> I dont know how to configure it in Proxmox, if you understand Qemu config you may see this [file](https://github.com/kholia/OSX-KVM/blob/master/boot-passthrough.sh).
> 
> I was able to boot macOS Monterey with RX580 successfully.

Thank you so much, I have a question please, you meant that you don't use Proxmox, so which one do you use to install macOS Monterey, I just know Hackintosh and Proxmox to do that.

**Comment by thunfischente** [comment]
I see the file you wrote, I understand that you install Linux Ubuntu first, and use OSX-KVM to install macOS Monterey, right? It's wonderful way bro, I will read more to understand, thank you so much!

**Comment by mbagusrd** [comment]
> I see the file you wrote, I understand that you install Linux Ubuntu first, and use OSX-KVM to install macOS Monterey, right? It's wonderful way bro, I will read more to understand, thank you so much!

Yes you right, I'm not using proxmox because I need to work with linux mint/Ubuntu too, and I dont have time to reinstall my PC to run proxmox, so I prefer install Qemu and passthrough my RX580 to run macOS

**Comment by Lassebq** [comment]
I also have an RX 580 which I cannot get to work under macOS Ventura KVM. After changing -cpu=Penryn to -cpu=Haswell-noTSX my existing macos install (which I installed with -device virtio-vga instead of vfio) would start boot looping. "MacOS Base System" does boot though (still, only with vgpu), so I'm reinstalling.

To be clear I had no issue passing the same GPU to a linux and windows guest. It also worked with both VGPU and dGPU inside the VM

**Comment by Lassebq** [comment]
Also, at least with windows guest I have to add `-device pcie-root-port,id=root_port1,addr=1c.0,chassis=1,slot=1,bus=pcie.0,multifunction=on` and specify `bus=root_port1` for passed through devices. If I keep it for macos the boot just freezes on empty progress bar (and in case of verbose mode it also freezes console log). Idk if that's just the way you're supposed to be doing it on newer qemu, but not having the root port doesn't freeze console, although the boot just never finishes. It's a very slow progress bar which goes by 1 pixel every 10 or so minutes
