### ISSUE TITLE
updating to BigSur

### ISSUE THREAD

**Issue by nferruzzi** [thenickdude/KVM-Opencore#5]
Hello,
has anyone tried to upgrade to BigSur RC1 from a working Catalina ? my setup works fine but I get stuck at EB|LOG:EXITBS:START when attempting to boot the installer disk downloaded from the store and installed via the official App. 
I've tried to troubleshoot this problem following the opencore guides about getting stuck at EXITBS with no luck. .. so just out of curiosity, are my expectation to upgrade flawlessly too high or this should work out of the box? 
thanks and sorry if this is the wrong place to ask :) 

Edit: Im using archlinux and libvirt to run the VM with GPU passthrough (RX580) and a proper AirDrop wifi passthrough too

**Comment by thenickdude** [comment]
You'll need to top first update to my OpenCore v9 release to boot Big Sur.

Comment out your GPU passthrough for the upgrade and put vga:vmware in its place. This avoids problems with GPU resetting during the multiple reboots needed for the upgrade.

**Comment by nferruzzi** [comment]
thank you, it works! Im actually replying from bigsur :) .. are these patches going to be included in the next versions of OpenCore ?

**Comment by thenickdude** [comment]
Great!

The only patch I had to make was to drop a change from the VBoxHFS driver to allow Catalina to continue to boot. I'm not sure if the default OpenCore distribution actually uses this driver, so maybe they won't bother to change it. Also I'm not sure why the patch, which looks like it does fix an actual bug, causes Catalina to fail to boot, it's strange.
