### ISSUE TITLE
Memory doesn't show informamtion

### ISSUE THREAD

**Issue by thunfischente** [thenickdude/KVM-Opencore#52]
![image](https://user-images.githubusercontent.com/74177947/215239090-1579e33d-ff63-48ad-9d16-d189b03dee73.png)

Hello, I install successfully macOS using KVM-Opencore, but the memory just shows "32 GB RAM", it doesn't show full information as hackintosh, is there any way to fix it please, I tried to change SMBios to MacPro7,1 and use custommemory.plist as well as restrictevent.kext but nothing changes. Thank you so much for the time to read my issue!

**Comment by thenickdude** [comment]
The memory display is purely cosmetic and does nothing, there's no point in setting that up.

**Comment by thunfischente** [comment]
> The memory display is purely cosmetic and does nothing, there's no point in setting that up.

thank you for your response!
