### ISSUE TITLE
There are some questions with using OpenCore in unraid，about vcpu

### ISSUE THREAD

**Issue by lxwsdtc88** [thenickdude/KVM-Opencore#69]
There are some  questions with using OpenCore in unraid：
        The CPU I am using is i5-8600, which has 6 cores and 6 threads. When I use 6 cores to create a virtual machine, it cannot pass and reports error # [EB | LOG: EXITBS: START]. 
       However, when I use 4 cores to create a virtual machine, it works, which has been bothering me for a long time. I hope someone can guide me. Thank you！

**Comment by thenickdude** [comment]
Pass 3 sockets and 2 cores instead (total 6 cores)
