### ISSUE TITLE
How to use on QEMU?

### ISSUE THREAD

**Issue by AnErrupTion** [thenickdude/KVM-Opencore#7]
Hello there!
I would like to know how to use the "OpenCore-v10.iso.gz" file for QEMU. I've tried converting it as a qcow2 file then booting it but it doesn't work. Any advice? I know it says it's for Proxmox but if there's any way it can be used for QEMU it would be really nice.

**Comment by thenickdude** [comment]
This is a raw disk image, if you unzip it and rename it .img you can attach
it as a disk (e.g. as a sata disk), pointing to it with file=.

**Comment by AnErrupTion** [comment]
Thanks! I didn't know it was a raw disk image :v

**Comment by thenickdude** [comment]
It has the extremely misleading extension of "iso" because I want to abuse the Proxmox ISO picker to select it from disk, then change the CD drive into a disk drive afterwards 😁
