### ISSUE TITLE
How to update OpenCore?

### ISSUE THREAD

**Issue by danrichardson** [thenickdude/KVM-Opencore#9]
There was a change from 0.6.5 -> Present (0.6.6?) where it no longer needs BootStrap.efi and just OpenCore.efi.  From a configuration perspective, are you planning on posting a v11 of your image?  I don't think the current image supports 11.2.3 (current release of Big Sur)

**Comment by thenickdude** [comment]
The current image boots Big Sur 11.2.3 fine, I'm running that version myself now and I didn't update OpenCore. 

Yes, I'll make a v11 eventually.

**Comment by danrichardson** [comment]
You're right.  It must have been my previous issues with disk writing that caused the update to fail.  I just ran the update to 11.2.3 and it worked great!

**Comment by thenickdude** [comment]
I've pushed a new v11 version now, though I'm not sure if there are any direct benefits to us in this version.
